### PR TITLE
NovaSeq SP support

### PR DESCRIPTION
**Pull request by monikaBrandt**
In this PR quality thresholds for NovaSeq SP are added to the configuration file. Since no testdata is available I did the assumption that RunParameters.xml will look the same for all NovaSeq runs. However, this is not confirmed by Illumina Tech support. Please, do not merge before this is confirmed.

### CODE REVIEW

**Review by johandahlberg — APPROVED** [review]

**Comment by johandahlberg** [comment]
Looks good to me. I haven't tried in on a SP flowcell, but it guess you have? I'm good to merge unless you want @MatildaAslin to also have a look. Great work!

**Comment by monikaBrandt** [comment]
According to Illumina Tech support they can't tell us anything about the NovaSeq SP run output with certainty. However, they answer that it should be safe to make the assumption that the output is the same as for other NovaSeq runs.

**Comment by monikaBrandt** [comment]
@johandahlberg There is no test data available for NovaSeq SP. We have to decide if we want to merge anyway. See previous comments.

**Comment by johandahlberg** [comment]
Well I think that we can merge this now, and then make adjustments as needed later. Do you want me to wait for @MatildaAslins review, or should I merge?

**Review by matrulda — APPROVED** [review]
Nice! Checked the values against INS-00123, looks correct. :+1:

**Pull request merged**
